name: GiveClock
version: 0.1.1
description: Give the player a clock when they join the server.
author: Midnight-2004
main: top.midnight.giveclock.GiveClock
api-version: 1.12

commands:
  giveclock:
    description: Plugin management command
    usage: /giveclock <help|version|reload>

permissions:
  giveclock.reload:
    description: Allow reloading the plugin configuration
    default: op
  giveclock.giveclock:
    description: Allow players to receive a clock when they join the server
    default: true